[tool.poetry]
name = "nixos-ssh"
version = "0.1.0"
description = ""
authors = ["Alejando VF <worshipingsheep.3@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
